"""Validation against the vendored official A2A JSON Schema bundle.

The bundle (src/a2a_scorecard/vendor/a2a-v1.0.1.json) is generated by the
A2A project from spec/a2a.proto. Its definitions are keyed by human titles
("Agent Card") while cross-references use proto-derived relative URIs
("lf.a2a.v1.AgentCard.jsonschema.json", "google.protobuf.Struct.jsonschema.json").
Flattening a title by removing spaces yields exactly the PascalCase name used
in those URIs; _retrieve exploits that to resolve every reference from the
single vendored file. See docs/adr/0004-vendored-spec-schema.md.
"""

from __future__ import annotations

import json
from functools import cache
from importlib import resources
from typing import Any

from jsonschema import Draft202012Validator
from referencing import Registry, Resource
from referencing.exceptions import NoSuchResource

SCHEMA_RESOURCE = "a2a-v1.0.1.json"


@cache
def bundle() -> dict[str, Any]:
    text = resources.files("a2a_scorecard.vendor").joinpath(SCHEMA_RESOURCE).read_text()
    data: dict[str, Any] = json.loads(text)
    return data


@cache
def _definitions_by_flat_name() -> dict[str, Any]:
    return {title.replace(" ", ""): schema for title, schema in bundle()["definitions"].items()}


def _retrieve(uri: str) -> Resource[Any]:
    name = uri.rsplit("/", 1)[-1].removesuffix(".jsonschema.json").rsplit(".", 1)[-1]
    schema = _definitions_by_flat_name().get(name)
    if schema is None:
        raise NoSuchResource(uri)
    return Resource.from_contents(schema)


@cache
def _validator_for(definition_title: str) -> Draft202012Validator:
    schema = bundle()["definitions"][definition_title]
    # The runtime API is Registry(retrieve=...); the attrs-generated stub
    # exposes the private field name, which mypy rejects.
    registry: Registry[Any] = Registry(retrieve=_retrieve)  # type: ignore[call-arg]
    return Draft202012Validator(schema, registry=registry)


def validate_against(definition_title: str, instance: Any) -> list[str]:
    """Return sorted human-readable error strings; empty list means valid."""
    validator = _validator_for(definition_title)
    errors = []
    for err in validator.iter_errors(instance):
        path = "$" + "".join(f"[{p!r}]" for p in err.absolute_path)
        errors.append(f"{path}: {err.message}")
    return sorted(errors)


def validate_agent_card(card: Any) -> list[str]:
    return validate_against("Agent Card", card)
